# ------------------------------------------------------------
# サイト基本情報
# ------------------------------------------------------------
title: あにまん検索【非公式】
description: |
  素人の作ったクソ雑魚低性能なあにまん掲示板専用の検索ツールの関連サイトです。
  あにまん掲示板の管理人ちゃんとは一切関係ありません。

# GitHub Pages の設定
baseurl: ""             # サブディレクトリ運用でなければ空文字
url: "https://animanman.github.io"

# どのテーマを使うか（Minima をいったん残す例）
theme: minima
markdown: kramdown

# ------------------------------------------------------------
# ナビゲーション
# ------------------------------------------------------------
# ここに増やしていけば、header.html で自動的にリンクが表示される
navigation:
  - title: "使い方"
    url: "/about/"
  - title: "その他"
    url: "/test/other/"

# ------------------------------------------------------------
# プラグイン
# ------------------------------------------------------------
plugins:
  - jekyll-seo-tag

# ------------------------------------------------------------
# 生成対象外ファイル（不要なものはここに追加）
# ------------------------------------------------------------
exclude:
  - README.md
  - script.js        # ルートに置いている余計な JS ファイル（必要に応じて削除）

